routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/admin', 'AdminController@index');
Route::get('/', 'UserController@index')->name('regist');
Route::post('/', 'UserController@sendRegist')->name('regist.post');
Route::get('/result/{name}', 'UserController@result')->name('regist.result');
Route::get('/home', 'HomeController@index')->name('home'); 
Route::delete('/back-form/{name}', 'UserController@removeData')->name('back.form');
Route::get('/set-kursi/{name}', 'UserController@seatSelection')->name('seat');
Route::post('/set-kursi/{name}', 'UserController@seatSelectionPost')->name('seat.post');
Auth::routes();
Auth::routes(['register' => false]);

// Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/logout', function(){
//     Auth::logout();

//     return redirect('/')->nmae('logout');
// });

// ADMIN
Route::get('/admin', 'AdminController@index')->name('admin');
Route::get('users/export/', 'GerejaController@export')->name('export');
// Route::get('/', 'AdminController@index')->name('admin');
Route::get('/logout', 'AdminController@logout')->name('logout');

// SEAT
Route::resource('/admin/kursi', 'SeatController');
Route::get('/admin/kursi', 'SeatController@kursi')->name('kursi');
Route::get('/admin/kursi/setKursi/{id}', 'SeatController@setKursi')->name('setKursi');

Route::get('/admin/kursi/setActive/{id}/{kursi}', 'SeatController@setActive')->name('active');
Route::get('/admin/kursi/setTidak/{id}/{kursi}', 'SeatController@setTidak')->name('tidak');

// FROM
Route::resource('/admin/form', 'FormController');
Route::get('/admin/memenuhiSyarat', 'FormController@memenuhiSyarat')->name('memenuhi');
Route::get('/admin/export/success', 'FormController@exportSuccess')->name('export.success');
Route::get('/admin/export/failed', 'FormController@exportFailed')->name('export.failed');
Route::get('/admin/export', 'FormController@exportAll')->name('export.all');
Route::get('/admin/tidakMemenuhiSyarat', 'FormController@tidakMemenuhiSyarat')->name('tidakMemenuhi');
Route::get('/admin/memenuhiSyarat/export', 'FormController@exportCsv1')->name('export1');
Route::get('/admin/tidakMemenuhiSyarat/export', 'FormController@exportCsv2')->name('export2');

// GEREJA
Route::resource('/admin/gereja', 'GerejaController');


Route::get('/home', 'HomeController@index')->name('home');
// WORSHIP
Route::resource('/admin/worship', 'WorshipsController');

// AGE
Route::resource('/admin/age', 'AgeController');
Route::get('/admin/age/export', 'AgeController@ageExportCsv')->name('ageExport');

app/Models/Gereja.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Gereja extends Model
{
    use SoftDeletes;

    protected $table = 't_churchs';

    protected $fillable = [
        'id',
        'name',
        'seat',
        'no_telephone',
        'email',
        'address'
    ];
}

app/Http/Controllers/GerejaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Church;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Hash;

use App\Models\Gereja;
use Maatwebsite\Excel\Facades\Excel;
use App\Models\SeatChurch;

class GerejaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Gereja::all();

        return view('pages.gereja.index')->with([
            'items' => $items
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item = Gereja::all();

        return view('pages.gereja.create')->with([
            'item' => $item
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $data = $request->all();
        // Gereja::create($data);
        // return redirect()->route('gereja.index');
        $data = $request->all();
        $seat = (int)$data['seat'];
        $result = Gereja::create($data);
        for ($i=0; $i < $seat; $i++) { 
            SeatChurch::create([
                'churc_id' => $result['id'],
                'number' => $i+1,
                'status' => 'Active',
            ]);
        }
        return redirect()->route('gereja.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Gereja::findOrFail($id);

        return view('pages.gereja.edit')->with([
            'item' => $item
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $gereja = Gereja::findOrFail($id);
        // for ($i=0; $i < $data['seat']; $i++) { 
        //     SeatChurch::create([
        //         'churc_id' => $gereja['id'],
        //         'number' => $i+1,
        //         'status' => 'Active',
        //     ]);
        // }
        $gereja->update($data);
        return redirect()->route('gereja.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Gereja::findOrFail($id);
        $item->delete();

        return redirect()->route('gereja.index');
    }
}

resources/views/pages/gereja/create.blade.php
@extends('layouts.admin.default')
@section('content')
    <section class="section">
        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">

                        {{-- CARD HEADER --}}
                        <div class="card-header">
                            <div class="col-sm-12 col-md-6">
                                <h3>Create Gereja</h3>
                            </div>
                        </div>

                        {{-- CARD BODY --}}
                        <div class="card-body">
                            <form action="{{route('gereja.store')}}" method="POST">
                                @csrf
                                
                                <div class="form-group row">
                                    <label for="name" class="col-sm-2 col-form-label">Nama Gereja</label>
                                    <div class="col-sm-4">
                                      <input type="text" name="name" class="form-control">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="seat" class="col-sm-2 col-form-label">Bangku</label>
                                    <div class="col-sm-4">
                                      <input type="number" name="seat" class="form-control">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="no_telephone" class="col-sm-2 col-form-label">Nomor Telepon</label>
                                    <div class="col-sm-4">
                                      <input type="number" name="no_telephone" class="form-control">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="email" class="col-sm-2 col-form-label">Email</label>
                                    <div class="col-sm-4">
                                      <input type="email" name="email" class="form-control">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="address" class="col-sm-2 col-form-label">Alamat</label>
                                    <div class="col-sm-4">
                                      {{-- <input type="text" name="address" class="form-control"> --}}
                                      <textarea name="address" id="address" cols="35" rows="5"></textarea>
                                    </div>
                                </div>

                                    <button type="submit" class="btn btn-primary float-right col-md-2">Tambah</button>

                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/pages/gereja/edit.blade.php
@extends('layouts.admin.default')
@section('content')
    <section class="section">
        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">

                        {{-- CARD HEADER --}}
                        <div class="card-header">
                            <div class="col-sm-12 col-md-6">
                                <h3>Edit Gereja</h3>
                            </div>
                        </div>

                        {{-- CARD BODY --}}
                        <div class="card-body">
                            <form action="{{route('gereja.update', $item->id)}}" method="POST">
                                @method('PUT')
                                @csrf
                                <div class="form-group row">
                                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                                    <div class="col-sm-4">
                                      <input type="text" name="name" value="{{$item->name}}" class="form-control">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="seat" class="col-sm-2 col-form-label">Seat</label>
                                    <div class="col-sm-4">
                                      <input type="number" name="seat" value="{{$item->seat}}" class="form-control">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="address" class="col-sm-2 col-form-label">Address</label>
                                    <div class="col-sm-4">
                                      {{-- <input type="text" name="address" class="form-control"> --}}
                                      <textarea name="address" id="address" cols="35" rows="5">{{$item->address}}</textarea>
                                    </div>
                                </div>

                                    <button type="submit" class="btn btn-primary float-right col-md-2">Ubah</button>

                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/pages/gereja/index.blade.php
@extends('layouts.admin.default')
@section('content')
    <section class="section">
        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">

                        {{-- CARD HEADER --}}
                        <div class="card-header">
                            <div class="col-sm-12 col-md-6">
                                <h3>Gereja</h3>
                            </div>
                            <div class="col-sm-12 col-md-6">
                                <a href="{{route('gereja.create')}}" class="btn btn-light float-right">
                                    Tambah
                                </a>
                            </div>
                        </div>
                        {{-- <a href="{{route('export')}}" class="btn btn-success">export</a> --}}
                        {{-- CARD BODY --}}
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-striped" id="table">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Nama Gereja</th>
                                            <th>Bangku</th>
                                            <th>Alamat</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @php
                                            $no =1;
                                        @endphp 
                                        
                                        @foreach ($items as $item)
                                        
                                        <tr>
                                            <td>{{$no++}}</td>
                                            <td>{{$item->name}}</td>
                                            <td>{{$item->seat}}</td>
                                            {{-- <td>{{$item->no_telephone}}</td> --}}
                                            {{-- <td>{{$item->email}}</td> --}}
                                            <td>{{$item->address}}</td>
                                            <td>
                                                {{-- <a href="#" class= "btn btn-info btn-sm">
                                                <i class="fa fa-eye"></i>
                                                </a> --}}
                                               <div class="row">
                                                <a href="{{route('gereja.edit', $item->id)}}" class="btn btn-primary btn-sm">
                                                    <i class="fas fa-pencil-alt"></i>
                                                </a>
                                                <form action="{{route('gereja.destroy', $item->id)}}" method="post" class="d-inline">
                                                    @csrf
                                                    @method('delete')
                                                    <button class="btn btn-danger btn-sm">
                                                    <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                               </div>
                                            </td>
                                        </tr>

                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection