routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/admin', 'AdminController@index');
Route::get('/', 'UserController@index')->name('regist');
Route::post('/', 'UserController@sendRegist')->name('regist.post');
Route::get('/result/{name}', 'UserController@result')->name('regist.result');
Route::get('/home', 'HomeController@index')->name('home'); 
Route::delete('/back-form/{name}', 'UserController@removeData')->name('back.form');
Route::get('/set-kursi/{name}', 'UserController@seatSelection')->name('seat');
Route::post('/set-kursi/{name}', 'UserController@seatSelectionPost')->name('seat.post');
Auth::routes();
Auth::routes(['register' => false]);

// Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/logout', function(){
//     Auth::logout();

//     return redirect('/')->nmae('logout');
// });

// ADMIN
Route::get('/admin', 'AdminController@index')->name('admin');
Route::get('users/export/', 'GerejaController@export')->name('export');
// Route::get('/', 'AdminController@index')->name('admin');
Route::get('/logout', 'AdminController@logout')->name('logout');

// SEAT
Route::resource('/admin/kursi', 'SeatController');
Route::get('/admin/kursi', 'SeatController@kursi')->name('kursi');
Route::get('/admin/kursi/setKursi/{id}', 'SeatController@setKursi')->name('setKursi');

Route::get('/admin/kursi/setActive/{id}/{kursi}', 'SeatController@setActive')->name('active');
Route::get('/admin/kursi/setTidak/{id}/{kursi}', 'SeatController@setTidak')->name('tidak');

// FROM
Route::resource('/admin/form', 'FormController');
Route::get('/admin/memenuhiSyarat', 'FormController@memenuhiSyarat')->name('memenuhi');
Route::get('/admin/export/success', 'FormController@exportSuccess')->name('export.success');
Route::get('/admin/export/failed', 'FormController@exportFailed')->name('export.failed');
Route::get('/admin/export', 'FormController@exportAll')->name('export.all');
Route::get('/admin/tidakMemenuhiSyarat', 'FormController@tidakMemenuhiSyarat')->name('tidakMemenuhi');
Route::get('/admin/memenuhiSyarat/export', 'FormController@exportCsv1')->name('export1');
Route::get('/admin/tidakMemenuhiSyarat/export', 'FormController@exportCsv2')->name('export2');

// GEREJA
Route::resource('/admin/gereja', 'GerejaController');


Route::get('/home', 'HomeController@index')->name('home');
// WORSHIP
Route::resource('/admin/worship', 'WorshipsController');

// AGE
Route::resource('/admin/age', 'AgeController');
Route::get('/admin/age/export', 'AgeController@ageExportCsv')->name('ageExport');

app/Models/Ages.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;

class Ages extends Model
{
    use SoftDeletes;

    protected $table = 't_ages';

    protected $fillable = [
        'id',
        'number',
    ];
}

app/Http/Controllers/AgeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Ages;

class AgeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Ages::paginate(25);

        return view('pages.age.index')->with([
            'items' => $items
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item = Ages::all();

        return view('pages.age.create')->with([
            'item' => $item
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        Ages::create($data);
        return redirect()->route('age.index');
    }

    public function ageExportCsv(Request $request)
    {
        $fileName = 'age.csv';
        $tasks = Ages::all();

        $headers = array(
            "Content-type"        => "text/csv",
            "Content-Disposition" => "attachment; filename=$fileName",
            "Pragma"              => "no-cache",
            "Cache-Control"       => "must-revalidate, post-check=0, pre-check=0",
            "Expires"             => "0"
        );

        $columns = array('Title', 'Assign', 'Description', 'Start Date', 'Due Date');

        $callback = function () use ($tasks, $columns) {
            $file = fopen('php://output', 'w');
            fputcsv($file, $columns);

            foreach ($tasks as $task) {
                $row['Title']  = $task->title;
                $row['Assign']    = $task->assign->name;
                $row['Description']    = $task->description;
                $row['Start Date']  = $task->start_at;
                $row['Due Date']  = $task->end_at;

                fputcsv($file, array($row['Title'], $row['Assign'], $row['Description'], $row['Start Date'], $row['Due Date']));
            }

            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Ages::findOrFail($id);
        $item->delete();

        return redirect()->route('age.index');
    }
}

resources/views/pages/age/create.blade.php
@extends('layouts.admin.default')
@section('content')
    <section class="section">
        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">

                        {{-- CARD HEADER --}}
                        <div class="card-header">
                            <div class="col-sm-12 col-md-6">
                                <h3>Create Usia</h3>
                            </div>
                        </div>

                        {{-- CARD BODY --}}
                        <div class="card-body">
                            <form action="{{route('age.store')}}" method="POST">
                                @csrf
                                
                                <div class="form-group row">
                                    <label for="number" class="col-sm-2 col-form-label">Usia</label>
                                    <div class="col-sm-4">
                                      <input type="number" name="number" class="form-control">
                                    </div>
                                </div>

                                    <button type="submit" class="btn btn-primary float-right col-md-2">Tambah</button>

                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/pages/age/index.blade.php
@extends('layouts.admin.default')
@section('content')
    <section class="section">
        <div class="section-body">
            <div class="row">
                <div class="col-12">
                    <div class="card">

                        {{-- CARD HEADER --}}
                        <div class="card-header">
                            <div class="col-sm-12 col-md-6">
                                <h3>Usia</h3>
                            </div>
                            <div class="col-sm-12 col-md-6">
                                <a href="{{route('age.create')}}" class="btn btn-light float-right">
                                    Create
                                </a>
                            </div>
                        </div>

                        {{-- CARD BODY --}}
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-striped" id="table">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Usia</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {{-- @php
                                            $no =1;
                                        @endphp  --}}
                                        
                                        @foreach ($items as $no => $item)
                                        
                                        <tr>
                                            <td>{{$no + $items->firstItem()}}</td>
                                            <td>{{$item->number}}</td>
                                            <td>
                                                <a href="{{route('gereja.edit', $item->id)}}" class="btn btn-primary btn-sm">
                                                    <i class="fas fa-pencil-alt"></i>
                                                </a>
                                                <form action="{{route('age.destroy', $item->id)}}" method="post" class="d-inline">
                                                    @csrf
                                                    @method('delete')
                                                    <button class="btn btn-danger btn-sm">
                                                    <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>

                                        @endforeach
                                    </tbody>

                        </table>
                        <div class="form-group">
                        <span data-href="{{route('ageExport')}}" id="export" class="btn btn-success btn-sm" onclick="exportTasks(event.target);">Export</span>
                    </div>
                                {{$items->links()}}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection